version: '3.8'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - azuremyst-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mangosd:
    build:
      context: .
      dockerfile: etc/docker/Dockerfile
      target: mangosd
    ports:
      - 8085:8085
      - 7878:7878
    volumes:
      - ./data:/azuremyst/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  realmd:
    build:
      context: .
      dockerfile: etc/docker/Dockerfile
      target: realmd
    ports:
      - 3724:3724
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  azuremyst-db:
    external: true