version: "3.7"

services:

    mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        volumes:
            - ./etc/mariadb/mariadb-init.sql:/docker-entrypoint-initdb.d/init.sql
            - azuremyst-db:/var/lib/mysql
        secrets:
            - sql-password-root
            - sql-username
            - sql-password
        environment:
            - MARIADB_USER_FILE=/run/secrets/sql-username
            - MARIADB_PASSWORD_FILE=/run/secrets/sql-password
            - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/sql-password-root
        restart: always
    
    web:
        depends_on:
            - mariadb
        build:
            context: .
            dockerfile: etc/docker/web-debug.Dockerfile
        secrets:
            - mangos-host
            - mangos-port
            - mangos-username
            - mangos-password
            - discord-clientid
            - discord-clientsecret
            - discord-bottoken
            - paypal-clientid
            - paypal-clientsecret
            - sql-server
            - sql-username
            - sql-password
            - sql-database
            - smtp-host
            - smtp-port
            - smtp-username
            - smtp-password
            - smtp-fromname
            - smtp-fromaddress
        environment:
            - APPLICATION__MANGOSOPTIONS__HOST=/run/secrets/mangos-host
            - APPLICATION__MANGOSOPTIONS__PORT=/run/secrets/mangos-port
            - APPLICATION__MANGOSOPTIONS__USERNAME=/run/secrets/mangos-username
            - APPLICATION__MANGOSOPTIONS__PASSWORD=/run/secrets/mangos-password
            - APPLICATION__DISCORDOPTIONS__CLIENTID=/run/secrets/discord-clientid
            - APPLICATION__DISCORDOPTIONS__SECRETID=/run/secrets/discord-clientsecret
            - APPLICATION__DISCORDOPTIONS__BOTTOKEN=/run/secrets/discord-bottoken
            - APPLICATION__PAYPALOPTIONS__CLIENTID=/run/secrets/paypal-clientid
            - APPLICATION__PAYPALOPTIONS__CLIENTSECRET=/run/secrets/paypal-clientsecret
            - APPLICATION__SQLCLIENTOPTIONS__SERVER=/run/secrets/sql-server
            - APPLICATION__SQLCLIENTOPTIONS__USERNAME=/run/secrets/sql-username
            - APPLICATION__SQLCLIENTOPTIONS__PASSWORD=/run/secrets/sql-password
            - APPLICATION__SQLCLIENTOPTIONS__DATABASE=/run/secrets/sql-database
            - APPLICATION__SMTPOPTIONS__HOST=/run/secrets/smtp-host
            - APPLICATION__SMTPOPTIONS__PORT=/run/secrets/smtp-port
            - APPLICATION__SMTPOPTIONS__USERNAME=/run/secrets/smtp-username
            - APPLICATION__SMTPOPTIONS__PASSWORD=/run/secrets/smtp-password
            - APPLICATION__SMTPOPTIONS__FROMNAME=/run/secrets/smtp-fromname
            - APPLICATION__SMTPOPTIONS__FROMADDRESS=/run/secrets/smtp-fromaddress
        restart: always

    nginx:
        depends_on:
            - mariadb
            - web
        build:
            context: .
            dockerfile: etc/docker/nginx-debug.Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: always

    realmd:
        depends_on:
            - mariadb
        build:
            context: .
            dockerfile: etc/docker/mangos-debug.Dockerfile
            target: realmd
        ports:
            - 3724:3724
        restart: always

    mangosd:
       depends_on:
           - mariadb
       build:
           context: .
           dockerfile: etc/docker/mangos-debug.Dockerfile
           target: mangosd
       ports:
          - 8085:8085
          - 7878:7878
       restart: always

secrets:

    mangos-host:
        file: secrets/mangos-host
    mangos-port:
        file: secrets/mangos-port
    mangos-username:
        file: secrets/mangos-username
    mangos-password:
        file: secrets/mangos-password
    discord-clientid:
        file: secrets/discord-clientid
    discord-clientsecret:
        file: secrets/discord-clientsecret
    discord-bottoken:
        file: secrets/discord-bottoken
    paypal-clientid:
        file: secrets/paypal-clientid
    paypal-clientsecret:
        file: secrets/paypal-clientsecret
    sql-server:
        file: secrets/sql-server
    sql-password-root:
        file: secrets/sql-password-root
    sql-username:
        file: secrets/sql-username
    sql-password:
        file: secrets/sql-password
    sql-database:
        file: secrets/sql-database
    smtp-host:
        file: secrets/smtp-host
    smtp-port:
        file: secrets/smtp-port
    smtp-username:
        file: secrets/smtp-username
    smtp-password:
        file: secrets/smtp-password
    smtp-fromname:
        file: secrets/smtp-fromname
    smtp-fromaddress:
        file: secrets/smtp-fromaddress
         
volumes:

    azuremyst-db:
        external: true
