namespace azuremyst.models.mangosd
{
    public partial class NpcText
    {
        public uint Id { get; set; }
        public string? Text00 { get; set; }
        public string? Text01 { get; set; }
        public byte Lang0 { get; set; }
        public float Prob0 { get; set; }
        public ushort Em00 { get; set; }
        public ushort Em01 { get; set; }
        public ushort Em02 { get; set; }
        public ushort Em03 { get; set; }
        public ushort Em04 { get; set; }
        public ushort Em05 { get; set; }
        public string? Text10 { get; set; }
        public string? Text11 { get; set; }
        public byte Lang1 { get; set; }
        public float Prob1 { get; set; }
        public ushort Em10 { get; set; }
        public ushort Em11 { get; set; }
        public ushort Em12 { get; set; }
        public ushort Em13 { get; set; }
        public ushort Em14 { get; set; }
        public ushort Em15 { get; set; }
        public string? Text20 { get; set; }
        public string? Text21 { get; set; }
        public byte Lang2 { get; set; }
        public float Prob2 { get; set; }
        public ushort Em20 { get; set; }
        public ushort Em21 { get; set; }
        public ushort Em22 { get; set; }
        public ushort Em23 { get; set; }
        public ushort Em24 { get; set; }
        public ushort Em25 { get; set; }
        public string? Text30 { get; set; }
        public string? Text31 { get; set; }
        public byte Lang3 { get; set; }
        public float Prob3 { get; set; }
        public ushort Em30 { get; set; }
        public ushort Em31 { get; set; }
        public ushort Em32 { get; set; }
        public ushort Em33 { get; set; }
        public ushort Em34 { get; set; }
        public ushort Em35 { get; set; }
        public string? Text40 { get; set; }
        public string? Text41 { get; set; }
        public byte Lang4 { get; set; }
        public float Prob4 { get; set; }
        public ushort Em40 { get; set; }
        public ushort Em41 { get; set; }
        public ushort Em42 { get; set; }
        public ushort Em43 { get; set; }
        public ushort Em44 { get; set; }
        public ushort Em45 { get; set; }
        public string? Text50 { get; set; }
        public string? Text51 { get; set; }
        public byte Lang5 { get; set; }
        public float Prob5 { get; set; }
        public ushort Em50 { get; set; }
        public ushort Em51 { get; set; }
        public ushort Em52 { get; set; }
        public ushort Em53 { get; set; }
        public ushort Em54 { get; set; }
        public ushort Em55 { get; set; }
        public string? Text60 { get; set; }
        public string? Text61 { get; set; }
        public byte Lang6 { get; set; }
        public float Prob6 { get; set; }
        public ushort Em60 { get; set; }
        public ushort Em61 { get; set; }
        public ushort Em62 { get; set; }
        public ushort Em63 { get; set; }
        public ushort Em64 { get; set; }
        public ushort Em65 { get; set; }
        public string? Text70 { get; set; }
        public string? Text71 { get; set; }
        public byte Lang7 { get; set; }
        public float Prob7 { get; set; }
        public ushort Em70 { get; set; }
        public ushort Em71 { get; set; }
        public ushort Em72 { get; set; }
        public ushort Em73 { get; set; }
        public ushort Em74 { get; set; }
        public ushort Em75 { get; set; }
    }
}
